/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jv;

import jv.FirstChapter.Second.Two;

public class App {
    

    public static void main(String[] args) {
        int [] a = {3, 4, 1, 1, 6};
        int k = 8;
       System.out.println( Two.findMin(k, a));
    }
}
